#########################################################################
#  _____  _                       _                             _       #
# |  __ \(_)                     | |                           | |      #
# | |  | |_ ___  ___ ___  _ __ __| |         __ _  __ _ _ __ __| | __ _ #
# | |  | | / __|/ __/ _ \| '__/ _` |        / _` |/ _` | '__/ _` |/ _` |#
# | |__| | \__ \ (_| (_) | | | (_| |       | (_| | (_| | | | (_| | (_| |#
# |_____/|_|___/\___\___/|_|  \__,_|        \__,_|\__,_|_|  \__,_|\__,_|#
#                                       ______                          #
#                                      |______|                         #
#########################################################################
bot:
  # Discord botunuzun tokeni
  token: ''
  # Discord botunuzun application idsi
  id: ''
  # Discord botunun durum kÄ±smÄ±
  status:
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event; playing = Oynuyor, streaming = YayÄ±nda, listening = Dinliyor, watching = Ä°zliyor, competing = YarÄ±ÅŸmada yarÄ±ÅŸÄ±yor.
    activity: 'streaming'
    # Discord botunun aÃ§Ä±klama yazÄ±sÄ±; %onDutyPolice% yazarak aktif mesaideki memurlarÄ±n sayÄ±sÄ±nÄ± gÃ¶sterebilirsiniz.
    text: '%onDutyPolice% kiÅŸi ÅŸuanda mesaide!'
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event streaming olarak ayarlanÄ±rsa aÅŸaÄŸÄ±daki twitch kÄ±smÄ±nÄ± doldurunuz.
    twitch: 'https://www.twitch.tv/example'
    # Discord botunun aktiflik kÄ±smÄ±; online = Aktif, idle = BoÅŸta, dnd = RahatsÄ±z Etmeyin, invisible = Ã‡evrimdÄ±ÅŸÄ±.
    status: 'idle'
guild:
  # Discord sunucunuzun idsi
  id: ''
settings:
  departmentName: 'LSPD'
  departmentLogo: 'https://static.wikia.nocookie.net/nopixel/images/4/43/LSPD3.png'
  departmentBanner: 'https://forum.cfx.re/uploads/default/original/4X/f/7/e/f7e79012c44e49af0a8f38dbb0d70dc324f3f9a7.png'
  departmentColor: '#0000ff'
  roles:
    # RÃ¼tbe rollerinin idleri
    officers: ['', '']
  channels:
    # Log kanalÄ±nÄ±n idsi
    log: ''
  # Mesaj iÃ§erikelrinde kulanÄ±lan emojiler, ğŸ“‹ ÅŸeklinde, :emojiAdÄ±: ÅŸeklinde veya idsiyle kullanÄ±labilir.
  emojis:
    department: 'ğŸ‘®'
    on: 'ğŸŸ©'
    off: 'ğŸŸ¥'
    warning: 'âš ï¸'
    info: 'ğŸ“‹'
    clock: 'â²ï¸'
commands:
    # Aktif mesaideki Ã¼yeleri gÃ¶steren komut
    activeDuty:
      # Bu komutu kullanabilmek iÃ§in gereken rol
      requiredRole: ''
